/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: npx qvac bundle sdk
 * Plugins: 1
 *
*   - @qvac/sdk/llamacpp-completion/plugin
 */

import { initializeWorkerCore, ensureRPCSetup } from "@qvac/sdk/worker-core";
import { registerPlugin } from "@qvac/sdk/plugins";
import { getServerLogger } from "@qvac/sdk/logging";

import { llmPlugin } from "@qvac/sdk/llamacpp-completion/plugin";

const { hasRPCConfig } = initializeWorkerCore();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: 1");

registerPlugin(llmPlugin);

// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
